name: Build
on:
  push:
    branches-ignore: [debian]

jobs:
  test:
    name: Ruby ${{ matrix.ruby }} / Redmine ${{ matrix.redmine }}
    runs-on: ubuntu-20.04

    strategy:
      matrix:
        ruby: ["2.6"]
        redmine: ["4.1.1"]
      fail-fast: false

    env:
      BUNDLE_JOBS: 4
      BUNDLE_PATH: ${{ github.workspace }}/vendor/bundle
      BUNDLE_RETRY: 3
      BUNDLE_WITHOUT: development
      REDMINE_VERSION: ${{ matrix.redmine }}

    steps:
      - uses: actions/checkout@master

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}

      - uses: actions/setup-node@v1
        with:
          node-version: 12

      - uses: actions/cache@v1
        with:
          path: vendor
          key: v2-ruby-${{ matrix.ruby }}-redmine-${{ matrix.redmine }}

      - name: setup postgres
        run: |
          sudo systemctl start postgresql
          sudo -u postgres createuser -s ${USER}

      - name: install ruby dependencies
        run: bundle install

      - name: install node dependencies
        run: npm ci --cache vendor/npm

      - name: setup redmine ${{ matrix.redmine }}
        run: ./redmine update

      - name: build frontend assets
        run: npm run build

      - name: run rspec spec/plugin
        run: ./redmine exec bundle exec rspec spec/plugin --color

      - name: run rspec spec/browser
        run: ./redmine exec bundle exec rspec spec/browser --color
