name: Test
on:
  push:
    branches-ignore: [debian]

jobs:
  test:
    name: Ruby ${{ matrix.ruby }} / Redmine ${{ matrix.redmine }}
    runs-on: ubuntu-20.04

    strategy:
      matrix:
        ruby: ["2.6", "2.5"]
        redmine: ["4.1.1", "4.0.7"]
      fail-fast: false

    env:
      BUNDLE_JOBS: 4
      BUNDLE_PATH: ${{ github.workspace }}/vendor/bundle
      BUNDLE_RETRY: 3
      BUNDLE_WITHOUT: development
      REDMINE_VERSION: ${{ matrix.redmine }}

    steps:
      - uses: actions/checkout@master

      - name: setup postgres
        run: |
          sudo systemctl start postgresql
          sudo -u postgres createuser -s ${USER}

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}

      - name: setup cache
        uses: actions/cache@v1
        with:
          path: vendor
          key: v2-ruby-${{ matrix.ruby }}-redmine-${{ matrix.redmine }}

      - name: install ruby dependencies
        run: bundle install

      - name: setup redmine ${{ matrix.redmine }}
        run: ./redmine update

      - name: run tests
        run: ./redmine exec bundle exec rspec --color
